### PR TITLE
Update gocov to support type parameters

### PR DESCRIPTION
**Pull request by nezorflame**
See https://github.com/axw/gocov/pull/91

### CODE REVIEW

**Comment by nezorflame** [comment]
@AlekSi ping :)

**Comment by AlekSi** [comment]
whoa

**Review by AlekSi — APPROVED** [review]

**Comment by AlekSi** [comment]
@nezorflame Do you want to become a maintainer?

**Comment by nezorflame** [comment]
If you need help with it, I can :)
Don't have a lot of free time but will help where/when I can.

**Pull request merged**
