### PR TITLE
adding source node suport,#fix the Jenkins Cobertura Plugin error:Source code is unavailable

### PR DESCRIPTION
**Pull request by Centny**

### CODE REVIEW

**Comment by dlsniper** [comment]
@AlekSi could you please find some time to merge this? Thank you!

**Comment by githubber84** [comment]
@AlekSi, @t-yuki 
I am not able to see what the failed/incomplete check is and why its failing in order to help fix the issue.
Could someone please either share more information about why this fix is not merged OR please resolve and merge the fix?
We have been waiting for a long time for this to be fixed.

**Comment by denouche** [comment]
Hi, what about this PR? I also need it.

Thanks

**Comment by danielleberre** [comment]
Hi @AlekSi , this PR would be very helpful in our case.

**Comment by lequanghoa** [comment]
Hi @AlekSi , this PR would be save my life

**Comment by AlekSi** [comment]
Can someone interested in this functionality rebase it to the current master?

**Comment by nvx** [comment]
I've rebased this onto master and opened a new PR #8 as requested.

**Comment by AlekSi** [comment]
Closed by #9.

**Pull request closed without merging**
