### PR TITLE
Calculate LineRate

### PR DESCRIPTION
**Pull request by marinbek**
I added code that calculates LineRate as well. Works fine on Shippable.

### CODE REVIEW

**Comment by 9len** [comment]
would love to see this merged.

**Comment by BlueDragonX** [comment]
1. This doesn't calculate the correct numbers for me. I have multiple coverage reports that are merged.
2. You really need to run gofmt on this.

**Comment by nalbion** [comment]
Thanks @marinbek I can see sequence coverage on Shippable now,

I noticed that I have an anonymous func which currently has an empty body, It's `line-rate` is reported as `NaN`

**Comment by AlekSi** [comment]
#7 is merged.

**Pull request closed without merging**
